import RssFeed from "./Base/RssFeed.js";

class TheCradleFeed extends RssFeed {
    facebook_link = "https://www.facebook.com/thecradlemedia/"
    instagram_link = "https://www.instagram.com/thecradlemedia/"
    twitter_link = "https://twitter.com/thecradlemedia"
    telegram_link = "https://t.me/cradlemedia"

    // The link to the site generated by the RSS feed should not be used to send people to
    LINK = "thecradle.co";
    constructor() {
        super('The Cradle', {
            host: "admin.thecradle.co",
            path: "/feed"
        });
    }
}

export default new TheCradleFeed()