import RssFeed from "./Base/RssFeed.js";

class TheCradleFeed extends RssFeed {
    // The link to the site generated by the RSS feed should not be used to send people to
    LINK = "thecradle.co";
    constructor() {
        super('The Cradle', {
            host: "admin.thecradle.co",
            path: "/feed"
        });
    }
}

export default new TheCradleFeed()